### PR TITLE
Adding hindi tanslation to document site

### LINKED ISSUE #132: Documentation - Translate to Hindi
Translate the documentation site to Hindi.

### PR DESCRIPTION
**Pull request by akadeepesh**
Related to #132

### CODE REVIEW

**Comment by castarco** [comment]
Hi @akadeepesh , thank you for your PR 😄 . I made a small change in its description because it does not close the issue completely (there are other pages that have to be translated as well).

I'll improve the issue description to list what's pending.

**Comment by akadeepesh** [comment]
Looking forward to it, guide me what all changes I should make. Thanks for the review.

**Review by castarco — APPROVED** [review]
lgtm

**Comment by akadeepesh** [comment]
> lgtm
👍

**Pull request merged**
