### PR TITLE
fix: removes duplicate base from resolved src

### PR DESCRIPTION
**Pull request by ndj91**
Fixes issue #144

### CODE REVIEW

**Comment by dnlek** [comment]
💯

**Comment by ndj91** [comment]
Hi @castarco,

How are you?
Just wondering if you've had a chance to look at this one?

**Comment by castarco** [comment]
Hi everyone, @ndj91 . I'm sorry I wasn't available for so long, it has been a long time of crushing load work for me. I'll be reviewing issues and PRs this weekend.

**Comment by castarco** [comment]
@ndj91 so far looks good, but the formatting is all off. Please run
- `pnpm format`
- `git commit --amend`
- `rebase -i main`
- `git push origin --force-with-lease`

Thank you for your effort 🙏🏻 .

**Comment by castarco** [comment]
@ndj91 I created a parallel PR (#158) including your commit with the change requests I mentioned here, your authorship is preserved, but the commit will appear as dual because of the formatting changes I included.

I'll be releasing your changes in a few minutes :) .

**Comment by ndj91** [comment]
Thanks for that, was also super busy with work and didn't see.

Appreciate you jumping on and getting this merge in asap

**Pull request closed without merging**
